# Generated by Django 2.2.5 on 2019-10-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('patronymic', models.CharField(blank=True, max_length=50)),
                ('number_phone', models.CharField(blank=True, max_length=11)),
                ('e_mail', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('web_site', models.CharField(blank=True, max_length=50)),
                ('file', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
