# Generated by Django 2.2.5 on 2019-10-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadingQrCode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
