# Generated by Django 2.2.5 on 2019-10-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadingQrCode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='time',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
