# Generated by Django 2.2.5 on 2019-10-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadingQrCode', '0002_card_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='time',
        ),
        migrations.AlterField(
            model_name='card',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='ReadingQrCode/static/img_qr'),
        ),
    ]
